### ISSUE TITLE
capitals in the name not supported

### ISSUE THREAD

**Issue by stelf** [darold/pgtt-rsl#2]
neither of these will produce a valid result

```
SELECT pgtt_schema.pgtt_create_table('TEST_TABLE', 'id integer, lbl text', true);
SELECT pgtt_schema.pgtt_create_table('"TEST_TABLE"', 'id integer, lbl text', true);
```

_suggestion: maybe have the names of entities (tables) quoted upon creation, as certain software recognizes capitals in names..._

**Comment by darold** [comment]
Fixed in current development code.
